"""Create ActionPlan model and relationships

Revision ID: 2e33cb19188f
Revises: 5c53503ca1c9
Create Date: 2026-02-03 12:46:37.194554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e33cb19188f'
down_revision: Union[str, None] = '5c53503ca1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
