"""Update Goal model to use Enums

Revision ID: 5c53503ca1c9
Revises: 9a54fd04eaf4
Create Date: 2026-02-03 10:52:03.147993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c53503ca1c9'
down_revision: Union[str, None] = '9a54fd04eaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DEBT_PAYOFF', 'EMERGENCY_FUND', 'SHORT_TERM_SAVING', 'FIRE_STARTER', name='goaltype'),
               existing_nullable=False,
               postgresql_using='type::goaltype')
    op.alter_column('goal', 'priority',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='goalpriority'),
               existing_nullable=False,
               postgresql_using='priority::goalpriority')
    op.alter_column('goal', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='goalstatus'),
               existing_nullable=False,
               postgresql_using='status::goalstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='goalstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('goal', 'priority',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='goalpriority'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('goal', 'type',
               existing_type=sa.Enum('DEBT_PAYOFF', 'EMERGENCY_FUND', 'SHORT_TERM_SAVING', 'FIRE_STARTER', name='goaltype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
